import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Apple Summary Slides',
  description: 'Generated by create next app',
  icons: {
    icon: './logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased min-h-screen bg-neutral-950`}>
        <Header />
        <Sidebar />
        <main className="flex-1 lg:pl-72 w-full pt-16 lg:pt-0 px-0">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
