/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdIndexRouteImport } from './routes/$id/index'
import { Route as IdCategoryIdRouteImport } from './routes/$id/$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdIndexRoute = IdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdCategoryIdRoute = IdCategoryIdRouteImport.update({
  id: '/$id/$categoryId',
  path: '/$id/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$id/$categoryId': typeof IdCategoryIdRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$id/$categoryId': typeof IdCategoryIdRoute
  '/$id': typeof IdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$id/$categoryId': typeof IdCategoryIdRoute
  '/$id/': typeof IdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$id/$categoryId' | '/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$id/$categoryId' | '/$id'
  id: '__root__' | '/' | '/$id/$categoryId' | '/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdCategoryIdRoute: typeof IdCategoryIdRoute
  IdIndexRoute: typeof IdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/': {
      id: '/$id/'
      path: '/$id'
      fullPath: '/$id/'
      preLoaderRoute: typeof IdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$id/$categoryId': {
      id: '/$id/$categoryId'
      path: '/$id/$categoryId'
      fullPath: '/$id/$categoryId'
      preLoaderRoute: typeof IdCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdCategoryIdRoute: IdCategoryIdRoute,
  IdIndexRoute: IdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
